### ISSUE TITLE
Adicionar pontos turísticos do Brasil

### ISSUE THREAD

**Issue by marcelabomfim** [marcelabomfim/conheca-o-brasil#10]
Vamos criar uma webapp com dicas de locais à se conhecer no Brasil, envie seu pull request com uma foto, nome e pequena descrição de algum ponto turístico brasileiro.

**Comment by Jefferson227** [comment]
Adicionado Feirinha da Beira Mar em Fortaleza, CE na PR #14 :)

**Comment by marcelabomfim** [comment]
boa :+1:

**Comment by rbezerra** [comment]
Adicionando dois pontos turísticos de São Luís-MA na PR #20
